# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Unity-iPhone' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	pod 'FBSDKLoginKit','12.0.0'
	pod 'Firebase/Analytics','7.3.0'
	pod 'Firebase/Messaging'
	pod 'Firebase/Crashlytics'
	pod 'GoogleSignIn','5.0.2'
	pod 'AppsFlyerFramework','~> 6.3.0'
	pod 'Bolts'
  # Pods for Unity-iPhone

  target 'Unity-iPhone Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'UnityFramework' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	pod 'FBSDKLoginKit','12.0.0'
	pod 'Firebase/Analytics','7.3.0'
	pod 'Firebase/Messaging'
	pod 'Firebase/Crashlytics'
	pod 'GoogleSignIn','5.0.2'
	pod 'AppsFlyerFramework','~> 6.3.0'
	pod 'Bolts'
  # Pods for UnityFramework

end
